int is_blank(char *s);
char *xerox(char *s);
char *center(char *s, int width);
int begins_with(char *s, char *pre);
int ends_with(char *s, char *suff);
char *remove_chars(char *s1, char *s2);
int index_of_first_difference(char *s1, char *s2);
void lstrip(char *s);
void rstrip(char *s);
void strip(char *s);
int find_idx(char *s, char c);
char *find_ptr(char *s, char c);
char *slice(char *s, int b, int e);
int strcmp_ign_case(char *s1, char *s2);
void str_glue(char *s1, char *s2);
char *ellipsize(char *s, int nw);
char *replace(char *s, char *pat, char *rep);
char **chop(char *s, char c);
